/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otopark1;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hasan
 */
public class araclar extends javax.swing.JFrame {

    /**
     * Creates new form araclar
     */
    public araclar() {
       super("Araçlar Formu");        
        initComponents();
        
        
   String baslik[] = new String[]{"Ad Soyad", "Plaka", "marka", "yas", "cep_no", "giris_cikis", "tarihi", "saati", "türü", "ucret", "toplam_ucret", "yerler" };  
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/otopark?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();
            
            String sorgu21 = "select * from araclar order by id desc";
            
            st = con.createStatement();
            rs = st.executeQuery(sorgu21);
            
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("ad_soyad"),  
                    rs.getString("plaka"),
                    rs.getString("marka"),
                    rs.getString("yas"),
                    rs.getString("cep_no"),  
                    rs.getString("giris_cikis"),
                    rs.getString("tarihi"),
                    rs.getString("saati"),                    
                    rs.getString("türü"),  
                    rs.getString("ucret"),
                    rs.getString("toplam_ucret"),
                    rs.getString("yerler"),
                    
                };
                i++;
            }
           
            table_araclar.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_yeri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_adi = new javax.swing.JTextField();
        txt_ucretleri = new javax.swing.JTextField();
        txt_marka = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_cikis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_araclar = new javax.swing.JTable();
        txt_cepno = new javax.swing.JTextField();
        txt_plaka = new javax.swing.JTextField();
        txt_türü = new javax.swing.JTextField();
        arac_ekle = new javax.swing.JButton();
        txt_yasi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        Arayuz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Saatlik Ücret");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 167, -1, -1));

        txt_yeri.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(txt_yeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 211, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Arac Yasi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 78, -1, -1));

        txt_adi.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(txt_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 74, 170, 30));

        txt_ucretleri.setBackground(new java.awt.Color(102, 255, 255));
        txt_ucretleri.setText("5");
        getContentPane().add(txt_ucretleri, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 163, 170, 30));

        txt_marka.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(txt_marka, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 117, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Cep Telefonu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 121, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Adı Soyadı");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 78, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Araç Türü");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 215, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Marka");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 121, -1, -1));

        btn_cikis.setBackground(new java.awt.Color(0, 204, 204));
        btn_cikis.setText("ÇIKIŞ");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 270, 170, 34));

        table_araclar.setBackground(new java.awt.Color(153, 255, 255));
        table_araclar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_araclar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_araclar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 340, 837, 225));

        txt_cepno.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(txt_cepno, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 117, 170, 30));

        txt_plaka.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(txt_plaka, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 163, 170, 30));

        txt_türü.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(txt_türü, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 211, 170, 30));

        arac_ekle.setBackground(new java.awt.Color(0, 204, 204));
        arac_ekle.setText("Kaydet");
        arac_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arac_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(arac_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 270, 170, 34));

        txt_yasi.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(txt_yasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 74, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Araç Plaka");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 167, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Araç Yeri");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 215, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText(" X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 0, 30, 38));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel10.setText("-");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 0, -1, 38));

        btn_Back.setBackground(new java.awt.Color(255, 255, 255));
        btn_Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Back.setText("<--");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Arayuz.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\icon\\p.a.jpg")); // NOI18N
        getContentPane().add(Arayuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed

        araclar ac = new araclar();
        ac.setVisible(false);
        dispose();

    }//GEN-LAST:event_btn_cikisActionPerformed

    private void arac_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arac_ekleActionPerformed

        try{
            // sistem tarihini aldık.
            String[] Aylar = { "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran",
                "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"};

            Calendar takvim = Calendar.getInstance();
            String tarih = takvim.get(Calendar.DATE) + " " + Aylar[takvim.get(Calendar.MONTH)]
            + " " + takvim.get(Calendar.YEAR);

            // sistem saatini aldık.
            SimpleDateFormat bicim3=new SimpleDateFormat("kk.mm");
            GregorianCalendar gcalender=new GregorianCalendar();

           String adi=txt_adi.getText();
            String marka=txt_marka.getText();
            String plaka=txt_plaka.getText();
            String tarihi=tarih;
            String saati=bicim3.format(gcalender.getTime());
            String yas=txt_yasi.getText();
            String tel=txt_cepno.getText();
            String ucretleri=txt_ucretleri.getText();
            String türü=txt_türü.getText();
            String yerler=txt_yeri.getText();

            if (adi.equals("") || plaka.equals("") || yerler.equals("")) {
                JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = null;
                Statement st = null;
                ResultSet rs = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost/otopark?useUnicode=true&characterEncoding=UTF-8", "root", "");
                st = con.createStatement();
                rs = st.executeQuery("select * from araclar where yerler='"+yerler+"' and giris_cikis='1'");
                rs.last();

                int sayi=rs.getRow();
                if(sayi>0){

                    JOptionPane.showMessageDialog(null, yerler+ " Nolu Yer Doludur!");

                }
                else{

                  st = con.createStatement();
                    String sql = "INSERT INTO araclar (ad_soyad,plaka,marka,yas,cep_no,tarihi,"
                            +"saati,türü,giris_cikis,ucret,yerler,toplam_ucret)" 
                        + " VALUES ('"+adi+"', '"+plaka+"', '"+marka+"', '"+yas+"', '"+tel+"',"
                        +"'"+tarihi+"', '"+saati+"','"+türü+"','1','"+ucretleri+"','"+yerler+"','0')";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "- "+ plaka + " <- Plakalı Araç Eklenmiştir.");
                    
                }
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }

    }//GEN-LAST:event_arac_ekleActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
      this.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        this.setVisible(false);  // register ekranını kapatıyoruz
        new Kontrol_Paneli().setVisible(true);// login ekranını tekrar açıyoruz.
    }//GEN-LAST:event_btn_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(araclar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(araclar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(araclar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(araclar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new araclar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arayuz;
    private javax.swing.JButton arac_ekle;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_cikis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_araclar;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_cepno;
    private javax.swing.JTextField txt_marka;
    private javax.swing.JTextField txt_plaka;
    private javax.swing.JTextField txt_türü;
    private javax.swing.JTextField txt_ucretleri;
    private javax.swing.JTextField txt_yasi;
    private javax.swing.JTextField txt_yeri;
    // End of variables declaration//GEN-END:variables
private void Seticon() {
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("91siyah.png")));   
    }
}
