/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otopark1;

import java.util.*;
import java.io.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;

/**
 *
 * @author hasan
 */
public class Kayit extends javax.swing.JFrame {

    /**
     * Creates new form Kayit
     */
  public Kayit(String unvani) {
        initComponents();
        Seticon();
        this.setLocationRelativeTo(null);
        
  }
  
     

      private Kayit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel68 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        txt_marka_model = new javax.swing.JTextField();
        txt_arac_turu = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        txt_id = new javax.swing.JPasswordField();
        jLabel70 = new javax.swing.JLabel();
        txt_plaka = new javax.swing.JTextField();
        txt_arac_yas = new javax.swing.JTextField();
        btn_kydt = new javax.swing.JButton();
        txt_ad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        btn_iptal = new javax.swing.JButton();
        txt_soyadi = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_k_adi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelRegister10 = new javax.swing.JLabel();
        Arayuz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setBackground(new java.awt.Color(255, 255, 255));
        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel68.setText("PLAKA:");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 272, -1, -1));

        jLabel65.setBackground(new java.awt.Color(255, 255, 255));
        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel65.setText("AD:");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 58, 60, -1));

        jLabel64.setBackground(new java.awt.Color(255, 255, 255));
        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel64.setText("ID:");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 188, -1, -1));

        txt_marka_model.setBackground(new java.awt.Color(108, 122, 137));
        txt_marka_model.setForeground(new java.awt.Color(228, 241, 254));
        txt_marka_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marka_modeltxt_plakaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_marka_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 370, 194, -1));

        txt_arac_turu.setBackground(new java.awt.Color(108, 122, 137));
        txt_arac_turu.setForeground(new java.awt.Color(228, 241, 254));
        getContentPane().add(txt_arac_turu, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 232, 194, -1));

        jLabel69.setBackground(new java.awt.Color(255, 255, 255));
        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel69.setText("ARAC YAŞI:");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 314, -1, -1));

        txt_id.setBackground(new java.awt.Color(108, 122, 137));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.setForeground(new java.awt.Color(228, 241, 254));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 189, 194, -1));

        jLabel70.setBackground(new java.awt.Color(255, 255, 255));
        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel70.setText("MARKA / MODEL:");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 370, -1, -1));

        txt_plaka.setBackground(new java.awt.Color(108, 122, 137));
        txt_plaka.setForeground(new java.awt.Color(228, 241, 254));
        txt_plaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_plakatxt_plakaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_plaka, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 274, 194, -1));

        txt_arac_yas.setBackground(new java.awt.Color(108, 122, 137));
        txt_arac_yas.setForeground(new java.awt.Color(228, 241, 254));
        getContentPane().add(txt_arac_yas, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 316, 194, -1));

        btn_kydt.setBackground(new java.awt.Color(34, 167, 240));
        btn_kydt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_kydt.setForeground(new java.awt.Color(255, 255, 255));
        btn_kydt.setText("kaydet");
        btn_kydt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kydtbtn_kydtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kydt, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 491, 91, 38));

        txt_ad.setBackground(new java.awt.Color(108, 122, 137));
        txt_ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ad.setForeground(new java.awt.Color(228, 241, 254));
        getContentPane().add(txt_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 59, 192, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cep Telefonu :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 419, -1, -1));

        jLabel66.setBackground(new java.awt.Color(255, 255, 255));
        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel66.setText("SOYAD:");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 103, -1));

        btn_iptal.setBackground(new java.awt.Color(242, 38, 19));
        btn_iptal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_iptal.setForeground(new java.awt.Color(255, 255, 255));
        btn_iptal.setText("iptal");
        btn_iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iptalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 491, 91, 38));

        txt_soyadi.setBackground(new java.awt.Color(108, 122, 137));
        txt_soyadi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_soyadi.setForeground(new java.awt.Color(228, 241, 254));
        getContentPane().add(txt_soyadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 101, 194, -1));

        txt_tel.setBackground(new java.awt.Color(108, 122, 137));
        txt_tel.setForeground(new java.awt.Color(228, 241, 254));
        getContentPane().add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 419, 194, 27));

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel67.setText("ARAC TÜRÜ:");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 230, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("KULLANICI ADI:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 142, -1, -1));

        txt_k_adi.setBackground(new java.awt.Color(108, 122, 137));
        txt_k_adi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_k_adi.setForeground(new java.awt.Color(228, 241, 254));
        getContentPane().add(txt_k_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 143, 194, -1));

        jPanel4.setBackground(new java.awt.Color(248, 148, 6));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KAYIT EKRANI");

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(jLabelMin)
                .addGap(6, 6, 6)
                .addComponent(jLabelClose)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMin)
                    .addComponent(jLabelClose))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelRegister10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRegister10.setText("giriş yapmak için tıkla !");
        jLabelRegister10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegister10jLabelRegister9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRegister10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, -1));

        Arayuz.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\icon\\kayit.1.jpg")); // NOI18N
        getContentPane().add(Arayuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 480, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_marka_modeltxt_plakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marka_modeltxt_plakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marka_modeltxt_plakaActionPerformed

    private void txt_plakatxt_plakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_plakatxt_plakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_plakatxt_plakaActionPerformed

    private void btn_kydtbtn_kydtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kydtbtn_kydtActionPerformed
        try{

            String ad = txt_ad.getText();
            String soyad = txt_soyadi.getText();
            String k_adi = txt_k_adi.getText();
            String id = txt_id.getText();
            String plaka = txt_plaka.getText();
            String tur = txt_arac_turu.getText();
            String yas = txt_arac_yas.getText();
            String model = txt_marka_model.getText();
            String cepno = txt_tel.getText();

            if (ad.equals("") || soyad.equals("") || k_adi.equals("") || id.equals("") || yas.equals("") || tur.equals("") || model.equals("") || cepno.equals("")) {
                JOptionPane.showMessageDialog(this, "Boş Alanları Doldurunuz.");
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = null;
                Statement st = null;
                ResultSet rs = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost/otopark?useUnicode=true&characterEncoding=UTF-8", "root", "");
                st = con.createStatement();

                String sql = "INSERT INTO uyeler (kadi,parola,cepno,unvan)"
                + " VALUES ('"+k_adi+"', '"+id+"', '"+cepno+"', '"+k_adi+"')";

                /*String sql1 = "INSERT INTO uyeler (k_adi,id)"
                + " VALUES ( '"+k_adi+"', '"+id+"')";

                st.executeUpdate(sql1);

                String sql = "INSERT INTO musteri (k_adi,parola,cepno)"
                + " VALUES ('"+k_adi+"', '"+id+"', '"+cepno+"')";*/

                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, " "+ k_adi + " Adlı Kullanıcı Eklenmiştir.");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }//GEN-LAST:event_btn_kydtbtn_kydtActionPerformed

    private void btn_iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iptalActionPerformed
     //  System.exit(0);
   this.setVisible(false);
        dispose();
        /*this.setVisible(false);  // register ekranını kapatıyoruz
        new Giris().setVisible(true);// login ekranını tekrar açıyoruz.**/

    }//GEN-LAST:event_btn_iptalActionPerformed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        this.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelRegister10jLabelRegister9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegister10jLabelRegister9MouseClicked
        Giris lgf = new Giris();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelRegister10jLabelRegister9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arayuz;
    private javax.swing.JButton btn_iptal;
    private javax.swing.JButton btn_kydt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegister10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_arac_turu;
    private javax.swing.JTextField txt_arac_yas;
    private javax.swing.JPasswordField txt_id;
    private javax.swing.JTextField txt_k_adi;
    private javax.swing.JTextField txt_marka_model;
    private javax.swing.JTextField txt_plaka;
    private javax.swing.JTextField txt_soyadi;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
private void Seticon() {
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("91siyah.png")));   
    }
}
